contrib/bootstrap: Fix indentation
Consistently indent using tabs (most of the file already used that)
and correct indentation for some switch cases.
(Whitespace-only changes)

diff --git a/contrib/bootstrap b/contrib/bootstrap
--- a/contrib/bootstrap
+++ b/contrib/bootstrap
@@ -201,40 +201,40 @@ add_make_enabled()
 
 check_ios_sdk()
 {
-    if test "$VLCSDKROOT"
-    then
-	    SDKROOT="$VLCSDKROOT"
-    else
+	if test "$VLCSDKROOT"
+	then
+		SDKROOT="$VLCSDKROOT"
+	else
 		if test -z "$SDKROOT"
 		then
-		   SDKROOT=`xcode-select -print-path`/Platforms/iPhone${PLATFORM}.platform/Developer/SDKs/iPhone${PLATFORM}${SDK_VERSION}.sdk
-		   echo "SDKROOT not specified, assuming $SDKROOT"
+			SDKROOT=`xcode-select -print-path`/Platforms/iPhone${PLATFORM}.platform/Developer/SDKs/iPhone${PLATFORM}${SDK_VERSION}.sdk
+			echo "SDKROOT not specified, assuming $SDKROOT"
 		else
-		   SDKROOT="$SDKROOT"
+			SDKROOT="$SDKROOT"
 		fi
-    fi
+	fi
 
-    if [ ! -d "${SDKROOT}" ]
-    then
-       echo "*** ${SDKROOT} does not exist, please install required SDK, or set SDKROOT manually. ***"
-       exit 1
-    fi
-    add_make "IOS_SDK=${SDKROOT}"
+	if [ ! -d "${SDKROOT}" ]
+	then
+		echo "*** ${SDKROOT} does not exist, please install required SDK, or set SDKROOT manually. ***"
+		exit 1
+	fi
+	add_make "IOS_SDK=${SDKROOT}"
 }
 
 check_macosx_sdk()
 {
-   if [ -z "$SDKROOT" ]; then
-      SDKROOT=$(xcrun --show-sdk-path)
-      echo "SDKROOT not specified, assuming $SDKROOT"
-   fi
+	if [ -z "$SDKROOT" ]; then
+		SDKROOT=$(xcrun --show-sdk-path)
+		echo "SDKROOT not specified, assuming $SDKROOT"
+	fi
 
-   if [ ! -d "$SDKROOT" ]; then
-      echo "*** $SDKROOT does not exist, please install required SDK, or set SDKROOT manually. ***"
-      exit 1
-   fi
+	if [ ! -d "$SDKROOT" ]; then
+		echo "*** $SDKROOT does not exist, please install required SDK, or set SDKROOT manually. ***"
+		exit 1
+	fi
 
-   add_make "MACOSX_SDK=${SDKROOT}"
+	add_make "MACOSX_SDK=${SDKROOT}"
 }
 
 check_android_sdk()
@@ -289,23 +289,23 @@ case "${OS}" in
 			add_make_enabled "HAVE_IOS" "HAVE_DARWIN_OS" "HAVE_BSD" "HAVE_FPU"
 
 			case "${HOST}" in
-			    *armv7s*)
-			    add_make "PLATFORM_SHORT_ARCH := armv7s"
-			    add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
-			    ;;
-			    *arm*)
-			    add_make "PLATFORM_SHORT_ARCH := armv7"
-			    add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
-			    ;;
-			    *arm64*|*aarch64*)
-			    add_make "PLATFORM_SHORT_ARCH := arm64"
-			    ;;
-			    *x86_64*)
-			    add_make "PLATFORM_SHORT_ARCH := x86_64"
-			    ;;
-			    *86*)
-			    add_make "PLATFORM_SHORT_ARCH := i386"
-			    ;;
+				*armv7s*)
+					add_make "PLATFORM_SHORT_ARCH := armv7s"
+					add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
+					;;
+				*arm*)
+					add_make "PLATFORM_SHORT_ARCH := armv7"
+					add_make_enabled "HAVE_NEON" "HAVE_ARMV7A"
+					;;
+				*arm64*|*aarch64*)
+					add_make "PLATFORM_SHORT_ARCH := arm64"
+					;;
+				*x86_64*)
+					add_make "PLATFORM_SHORT_ARCH := x86_64"
+					;;
+				*86*)
+					add_make "PLATFORM_SHORT_ARCH := i386"
+					;;
 			esac;
 		fi
 		if test "$BUILDFORTVOS"
@@ -321,20 +321,20 @@ case "${OS}" in
 		add_make_enabled "HAVE_LINUX" "HAVE_ANDROID"
 		case "${HOST}" in
 			*arm*)
-			add_make "PLATFORM_SHORT_ARCH := arm"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := arm"
+				;;
 			*arm64*|*aarch64*)
-			add_make "PLATFORM_SHORT_ARCH := arm64"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := arm64"
+				;;
 			*i686*)
-			add_make "PLATFORM_SHORT_ARCH := x86"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := x86"
+				;;
 			*x86_64*)
-			add_make "PLATFORM_SHORT_ARCH := x86_64"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := x86_64"
+				;;
 			*mipsel*)
-			add_make "PLATFORM_SHORT_ARCH := mips"
-			;;
+				add_make "PLATFORM_SHORT_ARCH := mips"
+				;;
 		esac
 		;;
 	*linux*)
@@ -343,11 +343,11 @@ case "${OS}" in
 			add_make_enabled "HAVE_TIZEN"
 			case "${HOST}" in
 				*arm*)
-				add_make "PLATFORM_SHORT_ARCH := arm"
-				;;
+					add_make "PLATFORM_SHORT_ARCH := arm"
+					;;
 				*i386*)
-				add_make "PLATFORM_SHORT_ARCH := x86"
-				;;
+					add_make "PLATFORM_SHORT_ARCH := x86"
+					;;
 			esac
 		fi
 
@@ -357,24 +357,24 @@ case "${OS}" in
 		add_make_enabled "HAVE_WIN32"
 		case "${HOST}" in
 			*winphone*|*windowsphone*)
-			add_make_enabled "HAVE_WINDOWSPHONE"
-			;;
+				add_make_enabled "HAVE_WINDOWSPHONE"
+				;;
 		esac
 		case "${HOST}" in
 			*winphone*|*windowsphone*|*winrt*|*uwp*)
-			add_make_enabled "HAVE_WINSTORE"
-			;;
+				add_make_enabled "HAVE_WINSTORE"
+				;;
 		esac
 		case "${HOST}" in
 			amd64*|x86_64*)
-			add_make_enabled "HAVE_WIN64"
-			;;
+				add_make_enabled "HAVE_WIN64"
+				;;
 		esac
-        case "${HOST}" in
-            armv7*)
-                add_make_enabled "HAVE_ARMV7A"
-                ;;
-        esac
+		case "${HOST}" in
+			armv7*)
+				add_make_enabled "HAVE_ARMV7A"
+				;;
+		esac
 		;;
 	*solaris*)
 		add_make_enabled "HAVE_SOLARIS"
