contrib: add option to build with advertising clause
This allows build contribs with 4-clause BSD license or similar.
This is not compatible with GPLv2.

diff --git a/contrib/bootstrap b/contrib/bootstrap
--- a/contrib/bootstrap
+++ b/contrib/bootstrap
@@ -32,6 +32,8 @@ usage()
 	echo "  --enable-small   optimize libraries for size with slight speed decrease [DANGEROUS]"
 	echo "  --disable-gpl    configure to not build viral GPL code"
 	echo "  --disable-gnuv3  configure to not build version 3 (L)GPL code"
+	echo "  --enable-ad-clauses configure to build packages with advertising clauses"
+	echo "                   (USE AT YOUR OWN LEGAL RISKS)"
 	echo "  --disable-optim  disable optimization in libraries"
 }
 
@@ -45,6 +47,7 @@ BUILD_NETWORK="1"
 BUILD_DISCS="1"
 GPL="1"
 GNUV3="1"
+AD_CLAUSES=
 WITH_OPTIMIZATION="1"
 
 if test ! -f "../../contrib/src/main.mak"
@@ -90,6 +93,9 @@ do
 		--disable-gnuv3)
 			GNUV3=
 			;;
+		--enable-ad-clauses)
+			AD_CLAUSES=1
+			;;
 		--disable-*)
 			PKGS_DISABLE="${PKGS_DISABLE} ${1#--disable-}"
 			;;
@@ -104,6 +110,12 @@ do
 	esac
 	shift
 done
+
+if test -n "$AD_CLAUSES" -a -n "$GPL" -a -z "$GNUV3"
+then
+	echo "Error: advertising clauses are not compatible with GPLv2!" >&2
+	exit 1
+fi
 
 if test -z "$BUILD"
 then
@@ -252,6 +264,7 @@ test -z "$BUILD_NETWORK" || add_make_enabled "BUILD_NETWORK"
 test -z "$ENABLE_SMALL" || add_make_enabled "ENABLE_SMALL"
 test -z "$GPL" || add_make_enabled "GPL"
 test -z "$GNUV3" || add_make_enabled "GNUV3"
+test -z "$AD_CLAUSES" || add_make_enabled "AD_CLAUSES"
 test -z "$WITH_OPTIMIZATION" || add_make_enabled "WITH_OPTIMIZATION"
 test "`uname -o`" != "Msys" || add_make "CMAKE_GENERATOR := -G \"MSYS Makefiles\""
 
