bootstrap: fail if pkg-config is absent
It is still possible to compile from tarball without pkg-config, though
the result will probably be quite useless.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -39,25 +39,16 @@ if test -d extras/contrib/build/bin; then
   fi
 fi
 
+# Check for pkg-config
+if ! "${PKG_CONFIG:-pkg-config}" --version >/dev/null 2>&1; then
+	echo 'Error: "pkg-config" is not installed.' >&2
+	exit 1
+fi
+
 # Prepare m4/private.m4
 rm -f m4/private.m4 && cat > m4/private.m4 << EOF
 dnl  Private VLC macros - generated by bootstrap
 EOF
-
-# Check for pkg-config
-if ! pkg-config --version >/dev/null 2>&1; then
-	cat << EOF
-NOTE: "pkg-config" is missing from your system.
-Many underlying libraries will not be detected.
-==============================================================
-
-EOF
-	cat >> m4/private.m4 << EOF
-dnl  User does not have pkg-config, so assume package was not found
-AC_DEFUN([PKG_CHECK_MODULES],[ifelse([\$4], , :, [\$4])])
-
-EOF
-fi
 
 # Check for autopoint (GNU gettext)
 export AUTOPOINT
