* ./src/misc/objects.c: two big changes in the object API: now objects can     only have one parent, because I don't want to deal with cycles, and each     created object is indexed in a global array. This feature is unused yet,     but it will speed up vlc_object_find(FIND_ANYWHERE).   * ./debian/rules: activated the faad codec.   * ./doc/fortunes.txt: new fortune cookies.   * ./modules/codec/mpeg_video/headers.c: reduced the use of attach/detach.   * ./modules/audio_output/oss.c: fixed two compilation warnings.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7108,7 +7108,7 @@ echo "configure:7097: checking for libfaad.a in ${with_faad_tree}" >&5
       faad_CFLAGS="${faad_CFLAGS} -I${real_faad_tree}/include"
     else
             echo "$ac_t""no" 1>&6
-      { echo "configure: error: cannot find ${real_faad_tree}/.libs/libfaad.a, make sure you compiled libfaad in ${with_faad_tree}" 1>&2; exit 1; }
+      { echo "configure: error: cannot find ${real_faad_tree}/libfaad/.libs/libfaad.a, make sure you compiled libfaad in ${with_faad_tree}" 1>&2; exit 1; }
     fi
   else
     CFLAGS="${save_CFLAGS} ${faad_CFLAGS}"
