libmad plug-in, courtesy of Jean-Paul Saman <jpsaman@wxs.nl>.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -747,11 +747,39 @@ dnl  rc plugin
 dnl
 AC_ARG_ENABLE(rc,
   [  --disable-rc            rc module (default enabled)])
-
 if test x$enable_rc != xno
 then
   BUILTINS="${BUILTINS} rc"
 fi
+
+dnl
+dnl  libmad plugin
+dnl
+AC_ARG_WITH(libmad,
+  [  --with-libmad[=PATH]    libmad module (default disabled)],
+  [ if test "x$with_val" != "xno"; then
+      if test -n $with_val; then
+	    CFLAGS_MAD_ADEC="-I$with_val/include"
+        LIB_MAD_ADEC="-L$with_val/lib -lmad"
+      else
+        LIB_MAD_ADEC="-lmad"
+      fi
+      save_CFLAGS=$CFLAGS
+      save_LDFLAGS=$LDFLAGS
+      CFLAGS="$CFLAGS $CFLAGS_MAD_ADEC"
+      LDFLAGS="$LDFLAGS $LIB_MAD_ADEC"
+      AC_CHECK_HEADERS(mad.h, ,
+      [ echo "Cannot find development headers for libmad..."
+        exit 1
+      ])
+      AC_CHECK_LIB(mad, mad_bit_init, ,
+      [ echo "Cannot find libmad library..."
+        exit 1
+      ])
+      CFLAGS=$save_CFLAGS
+      LDFLAGS=$save_LDFLAGS
+      PLUGINS="${PLUGINS} mad_adec"
+    fi ])
 
 dnl special case for BeOS
 if test x$SYS = xbeos
@@ -1203,6 +1231,7 @@ AC_SUBST(LIB_GTK)
 AC_SUBST(LIB_KDE)
 AC_SUBST(LIB_LIBDVDCSS)
 AC_SUBST(LIB_MACOSX)
+AC_SUBST(LIB_MAD_ADEC)
 AC_SUBST(LIB_NCURSES)
 AC_SUBST(LIB_QNX)
 AC_SUBST(LIB_QT)
@@ -1221,6 +1250,7 @@ AC_SUBST(CFLAGS_LIBDVDCSS)
 AC_SUBST(CFLAGS_ARTS)
 AC_SUBST(CFLAGS_ESD)
 AC_SUBST(CFLAGS_GTK)
+AC_SUBST(CFLAGS_MAD_ADEC)
 AC_SUBST(CFLAGS_SDL)
 AC_SUBST(CFLAGS_X11)
 
