Prepare for future darwin releases

diff --git a/extras/contrib/bootstrap b/extras/contrib/bootstrap
--- a/extras/contrib/bootstrap
+++ b/extras/contrib/bootstrap
@@ -169,6 +169,26 @@ case $HOST in
             exit 1
         fi
     ;;
+    i686-apple-darwin10d1)
+        SDK_TARGET=10.6
+        echo "SDK_TARGET = ${SDK_TARGET}" >> config.mak
+        echo "HAVE_DARWIN_OS_ON_INTEL = 1" >> config.mak
+        echo "HAVE_DARWIN_9 = 1" >> config.mak
+        echo "HAVE_DARWIN_10 = 1" >> config.mak
+        echo "ENVP = MACOSX_DEPLOYMENT_TARGET=${SDK_TARGET}" >> config.mak
+        echo "MACOSX_SDK = /Developer/SDKs/MacOSX10.6.sdk" >> config.mak
+        CFLAGS_TUNING=" -march=pentium-m -mtune=prescott"
+        EXTRA_CFLAGS=" -D\${ENVP} -isysroot \${MACOSX_SDK} -mmacosx-version-min=\${SDK_TARGET}"
+        EXTRA_LDFLAGS=" -isysroot \${MACOSX_SDK} -Wl,-syslibroot,\${MACOSX_SDK}"
+        echo "PATH = /bin:/usr/bin:/usr/local/bin" >> config.mak
+        cat src/Distributions/darwin.mak >> distro.mak
+        if test -e /Developer/SDKs; then
+            echo "SDKs found. Everything is fine." >&2
+        else
+            echo "ERROR:\nYour Developer Tools' SDKs were not found.\nYou need to add extra symbolic links to /Developer to achieve correctly\nbuilt contribs.\nHave a look at the OSX-Compile-HOWTO for details." >&2
+            exit 1
+        fi
+    ;;
     i586-pc-beos)
         if test -f /boot/beos/system/lib/libbind.so; then
             EXTRA_LDFLAGS=" -lbind -lsocket"
