extras/tools: bootstrap: Check tar for compression auto-detection
This checks both auto-compress in create mode based on archive suffix
and auto-detection in extract mode based on file magic.

I believe it's reasonable to assume that, if it works for gzip, it works
for all compression schemes.

GNU tar has supported auto-detecting since 1.15 [1] and auto-compress
since 1.20 [2].
bsdtar has supported auto-detecting since before their initial git
commit [3] and auto-compress since 3.1.0 [4].

[1] https://cgit.git.savannah.gnu.org/cgit/tar.git/commit/?id=4674867a23ed4b42b0a84102331d369f6fc7e467
[2] https://cgit.git.savannah.gnu.org/cgit/tar.git/commit/?id=620a136e74f211c2fb98b45fe44261d5d775f6a9
[3] https://github.com/libarchive/libarchive/blob/8f776fd9f7b07842fdb5801af7128808860cbe35/tar/bsdtar.1#L413
[4] https://github.com/libarchive/libarchive/commit/d06fc9e5e4a47d022188d4b10202873c5d995b6e

(cherry picked from commit e0a6f726a66ea369096919f3fd4a696a80cb71fd)
Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>

diff --git a/extras/tools/bootstrap b/extras/tools/bootstrap
--- a/extras/tools/bootstrap
+++ b/extras/tools/bootstrap
@@ -86,12 +86,25 @@ fi
 }
 
 check_tar() {
-if ! { check_tar_xz && check_tar_zstd ; }
+if ! { check_tar_autocompress && check_tar_xz && check_tar_zstd ; }
 then
     NEEDED="$NEEDED tar"
 else
     FOUND="$FOUND tar"
 fi
+}
+
+check_tar_autocompress() {
+tmp="check_tar"
+ret=0
+echo "Hello Cone" > "$tmp"
+if ! ( tar -caf "$tmp.tar.gz" "$tmp" && tar xfo "$tmp.tar.gz" )
+then
+    echo "tar can't auto-detect compression"
+    ret=1
+fi
+rm -f "$tmp" "$tmp.tar.gz" 2>/dev/null
+return "$ret"
 }
 
 check_tar_xz() {
