tools: always use a ninja version supporting jobserver
This will build contribs in a nicer way

(cherry picked from commit 106f0ea1320e3088c16ee717cee4af08f28cb016) (rebased)
rebased:
- the code around is slightly different

diff --git a/extras/tools/bootstrap b/extras/tools/bootstrap
--- a/extras/tools/bootstrap
+++ b/extras/tools/bootstrap
@@ -96,6 +96,28 @@ else
 fi
 }
 
+check_ninja() {
+if ! ninja --version >/dev/null 2>&1
+then
+    echo "ninja not found"
+    NEEDED="$NEEDED ninja"
+else
+    jobserver=`ninja --version | head -1 | grep .jobserver`
+    if [ -z "$jobserver" ]; then
+        echo "ninja missing jobserver support"
+        NEEDED="$NEEDED ninja"
+    else
+        # found, need to check version ?
+        if [ -z "$1" ];then
+            FOUND="$FOUND ninja"
+        else
+            gotver=`ninja --version | head -1 | sed s/'.* '//`
+            check_version ninja $gotver $1
+        fi
+    fi
+fi
+}
+
 check() {
 if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1
 then
@@ -145,7 +167,7 @@ check flex
 check_nasm 2.14
 check help2man
 check meson 0.60.0
-check ninja
+check_ninja
 check gettext
 
 DEPS_ONLY="help2man"
