extras/tools: boostrap: put the regular check first
So that others may call it.

No functional changes.

(cherry picked from commit 8e94b1a9b8ca5533ac57cc017659d051cf896913)
Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>

diff --git a/extras/tools/bootstrap b/extras/tools/bootstrap
--- a/extras/tools/bootstrap
+++ b/extras/tools/bootstrap
@@ -68,6 +68,22 @@ check_version_majmin() {
 
 }
 
+check() {
+if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1
+then
+    echo "$1 not found"
+    NEEDED="$NEEDED $1"
+else
+    # found, need to check version ?
+    if [ -z "$2" ];then
+        FOUND="$FOUND $1"
+    else
+        gotver=`$1 --version | head -1 | grep -o '[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?' | head -1`
+        check_version $1 $gotver $2
+    fi
+fi
+}
+
 check_tar() {
 if ! tar PcJ /dev/null >/dev/null 2>&1 && ! tar PcJf /dev/null /dev/null 2>&1
 then
@@ -125,22 +141,6 @@ else
             gotver=`ninja --version | head -1 | sed s/'.* '//`
             check_version ninja $gotver $1
         fi
-    fi
-fi
-}
-
-check() {
-if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1
-then
-    echo "$1 not found"
-    NEEDED="$NEEDED $1"
-else
-    # found, need to check version ?
-    if [ -z "$2" ];then
-        FOUND="$FOUND $1"
-    else
-        gotver=`$1 --version | head -1 | grep -o '[0-9]\+\.[0-9]\+\(\.[0-9]\+\)\?' | head -1`
-        check_version $1 $gotver $2
     fi
 fi
 }
