extras/tools: Add an intermediate build target
This allows us to have dependencies across targets, but without
rebuilding them when it's unnecessary

(cherry picked from commit ff2c7d928e669fdd1189e095b4a044c0cb887636) (edited)

edited:
- this branch already had ninja and meson
- this branch already created build/bin by default

Signed-off-by: Steve Lhomme <robux4@ycbcr.xyz>

diff --git a/extras/tools/bootstrap b/extras/tools/bootstrap
--- a/extras/tools/bootstrap
+++ b/extras/tools/bootstrap
@@ -17,6 +17,7 @@
 
 export LC_ALL=
 NEEDED=
+FOUND=
 
 if [ ! -f tools.mak ]
 then
@@ -39,7 +40,26 @@ check_version() {
          -o "$needmajor" -eq "$gotmajor" -a "$needminor" -eq "$gotminor" -a "$needmicro" -gt "$gotmicro" ]
     then
         echo "$1 too old"
-        NEEDED="$NEEDED .$1"
+        NEEDED="$NEEDED $1"
+    else
+        FOUND="$FOUND $1"
+    fi
+
+}
+
+check_version_majmin() {
+    gotver=$2
+    gotmajor=`echo $gotver|cut -d. -f1`
+    gotminor=`echo $gotver|cut -d. -f2`
+    needmajor=`echo $3|cut -d. -f1`
+    needminor=`echo $3|cut -d. -f2`
+    if [ "$needmajor" -ne "$gotmajor" \
+         -o "$needminor" -ne "$gotminor" ]
+    then
+        echo "$1 not compatible"
+        NEEDED="$NEEDED $1"
+    else
+        FOUND="$FOUND $1"
     fi
 
 }
@@ -48,7 +68,9 @@ check_tar() {
 if ! tar PcJ /dev/null >/dev/null 2>&1
 then
     echo "tar doesn't support xz (J option)"
-    NEEDED="$NEEDED .tar .xz"
+    NEEDED="$NEEDED tar xz"
+else
+    FOUND="$FOUND tar xz"
 fi
 }
 
@@ -59,7 +81,9 @@ echo "test file for GNU sed" > $tmp
 if ! sed -i -e 's/sed//' $tmp >/dev/null 2>&1
 then
     echo "sed doesn't do in-place editing (-i option)"
-    NEEDED="$NEEDED .sed"
+    NEEDED="$NEEDED sed"
+else
+    FOUND="$FOUND sed"
 fi
 }
 
@@ -67,7 +91,7 @@ check_nasm() {
 if ! nasm -v >/dev/null 2>&1
 then
     echo "nasm not found"
-    NEEDED="$NEEDED .nasm"
+    NEEDED="$NEEDED nasm"
 else
     # found, need to check version ?
     [ -z "$1" ] && return # no
@@ -80,12 +104,25 @@ check() {
 if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1
 then
     echo "$1 not found"
-    NEEDED="$NEEDED .$1"
+    NEEDED="$NEEDED $1"
 else
     # found, need to check version ?
     [ -z "$2" ] && return # no
     gotver=`$1 --version | head -1 | sed s/'.* '//`
     check_version $1 $gotver $2
+fi
+}
+
+check_majmin() {
+if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1 && ! $1 --version 2>/dev/null
+then
+    echo "$1 not found"
+    NEEDED="$NEEDED $1"
+else
+    # found, need to check version ?
+    [ -z "$2" ] && return # no
+    gotver=`$1 --version | head -1 | sed s/'.* '//`
+    check_version_majmin $1 $gotver $2
 fi
 }
 
@@ -109,7 +146,7 @@ check help2man
 check meson 0.51.1
 check ninja
 
-[ -n "$NEEDED" ] && mkdir -p build/bin && echo "To-be-built packages: `echo $NEEDED | sed 's/\.//g'`"
+[ -n "$NEEDED" ] && mkdir -p build/bin && echo "To-be-built packages: $NEEDED"
 
 CPUS=
 case `uname` in
@@ -135,8 +172,19 @@ cat > Makefile << EOF
 MAKEFLAGS += -j$CPUS
 CMAKEFLAGS += --parallel=$CPUS
 PREFIX=\$(abspath ./build)
+EOF
 
-all: $NEEDED
+for t in $FOUND; do
+    echo ".$t:" >> Makefile
+done
+
+for t in $NEEDED; do
+    echo .$t: .build$t >> Makefile
+    TARGETS="$TARGETS .build$t"
+done
+
+cat >> Makefile << EOF
+all: $TARGETS
 	@echo "You are ready to build VLC and its contribs"
 
 include tools.mak
