CI: don't use multiple lines in a for loop
For some reason gitlab doesn't like it.

It worked with the line

> for ext in exe msi 7z zip; do mv ${SHORTARCH}/vlc-*-dev-*.${ext} nightlies/$(basename ${SHORTARCH}/vlc-*-dev-*.${ext} | sed "s/\.${ext}/-${CI_COMMIT_SHORT_SHA}\.${ext}/"); done

It should work with the line

> for ext in exe msi 7z zip; do mv ${SHORTARCH}/vlc-*-dev-*.${ext} nightlies/$(basename ${SHORTARCH}/vlc-*-dev-*.${ext} | sed "s/\.${ext}/-${CI_COMMIT_SHORT_SHA}\.${ext}/") || echo "vlc-*.${ext} not found!"; done

diff --git a/extras/ci/gitlab-ci.yml b/extras/ci/gitlab-ci.yml
--- a/extras/ci/gitlab-ci.yml
+++ b/extras/ci/gitlab-ci.yml
@@ -192,16 +192,8 @@ uwp64-libvlc-llvm:
         - if: '$CI_PIPELINE_SOURCE == "schedule"'
     after_script:
         - mkdir nightlies
-        - for ext in 7z; \
-          do mv                  ${SHORTARCH}/vlc-*-dev-*-debug.${ext} \
-            nightlies/$(basename ${SHORTARCH}/vlc-*-dev-*-debug.${ext} | sed "s/\.${ext}/-${CI_COMMIT_SHORT_SHA}\.${ext}/") || \
-            echo "vlc-*debug.${ext} not found!"; \
-          done
-        - for ext in exe msi 7z zip; \
-           do mv                  ${SHORTARCH}/vlc-*-dev-*.${ext} \
-             nightlies/$(basename ${SHORTARCH}/vlc-*-dev-*.${ext}      | sed "s/\.${ext}/-${CI_COMMIT_SHORT_SHA}\.${ext}/") || \
-            echo "vlc-*.${ext} not found!"; \
-           done
+        - for ext in 7z;  do mv ${SHORTARCH}/vlc-*-dev-*-debug.${ext} nightlies/$(basename ${SHORTARCH}/vlc-*-dev-*-debug.${ext} | sed "s/\.${ext}/-${CI_COMMIT_SHORT_SHA}\.${ext}/") || echo "vlc-*debug.${ext} not found!"; done
+        - for ext in exe msi 7z zip; do mv ${SHORTARCH}/vlc-*-dev-*.${ext} nightlies/$(basename ${SHORTARCH}/vlc-*-dev-*.${ext} | sed "s/\.${ext}/-${CI_COMMIT_SHORT_SHA}\.${ext}/") || echo "vlc-*.${ext} not found!"; done
         - cd nightlies && find . -maxdepth 1 -type f -not -name SHA512SUM | xargs shasum -a 512 | tee SHA512SUM
     artifacts:
         paths:
